[program:fba_celery_worker]
directory=/fba/backend
# 使用 AsyncIOPool 支持 async def 任务
environment=CELERY_CUSTOM_WORKER_POOL="celery_aio_pool.pool:AsyncIOPool"
command=/usr/local/bin/celery -A app.task.celery worker -P custom -c 4 --loglevel=INFO
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/fba/fba_celery_worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5
