"""add_screenshot_fields_to_feedback

Revision ID: 71cc2d84933e
Revises: add_tenant_config_table
Create Date: 2025-12-28 08:02:05.322313

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '71cc2d84933e'
down_revision = 'add_tenant_config_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('screenshot_url', sa.Text(), nullable=True, comment='截图 OSS 地址'))
    op.add_column(
        'feedbacks',
        sa.Column(
            'source_platform',
            sa.String(length=50),
            nullable=True,
            comment='来源平台: wechat, xiaohongshu, appstore, weibo, other',
        ),
    )
    op.add_column(
        'feedbacks', sa.Column('source_user_name', sa.String(length=255), nullable=True, comment='来源平台用户昵称')
    )
    op.add_column(
        'feedbacks', sa.Column('source_user_id', sa.String(length=255), nullable=True, comment='来源平台用户 ID')
    )
    op.add_column(
        'feedbacks', sa.Column('ai_confidence', sa.Float(), nullable=True, comment='AI 识别置信度 (0.00-1.00)')
    )
    op.add_column(
        'feedbacks', sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='内部提交者（员工）ID')
    )
    op.alter_column(
        'feedbacks',
        'source',
        existing_type=sa.VARCHAR(length=20),
        comment='来源: manual, import, api, screenshot',
        existing_comment='来源: manual, import, api',
        existing_nullable=False,
    )
    op.create_foreign_key(
        'feedbacks_submitter_id_fkey', 'feedbacks', 'sys_user', ['submitter_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedbacks_submitter_id_fkey', 'feedbacks', type_='foreignkey')
    op.alter_column(
        'feedbacks',
        'source',
        existing_type=sa.VARCHAR(length=20),
        comment='来源: manual, import, api',
        existing_comment='来源: manual, import, api, screenshot',
        existing_nullable=False,
    )
    op.drop_column('feedbacks', 'submitter_id')
    op.drop_column('feedbacks', 'ai_confidence')
    op.drop_column('feedbacks', 'source_user_id')
    op.drop_column('feedbacks', 'source_user_name')
    op.drop_column('feedbacks', 'source_platform')
    op.drop_column('feedbacks', 'screenshot_url')
    # ### end Alembic commands ###
