"""fix_chinese_comments_encoding

Revision ID: 03e4ac7514e6
Revises: b2c3d4e5f6g7
Create Date: 2026-01-16 12:50:23.735825

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "03e4ac7514e6"
down_revision = "b2c3d4e5f6g7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenant_permissions",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment="权限代码，如 feedback:view",
        existing_comment="权限代码",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_permissions",
        "type",
        existing_type=sa.VARCHAR(length=20),
        comment="类型: module, action",
        existing_comment="类型",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_permissions",
        "menu_path",
        existing_type=sa.VARCHAR(length=256),
        comment="关联的菜单路径，如 /app/feedback",
        existing_comment="关联的菜单路径",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_permissions",
        "menu_icon",
        existing_type=sa.VARCHAR(length=64),
        comment="菜单图标，如 lucide:inbox",
        existing_comment="菜单图标",
        existing_nullable=True,
    )
    op.create_table_comment(
        "tenant_permissions", "租户权限表（全局定义，所有租户共享权限点）", existing_comment="租户权限表", schema=None
    )
    op.alter_column(
        "tenant_roles",
        "is_builtin",
        existing_type=sa.BOOLEAN(),
        comment="是否内置角色（不可删除）",
        existing_comment="是否内置角色",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_roles",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="状态: active, disabled",
        existing_comment="状态",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenant_roles",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="状态",
        existing_comment="状态: active, disabled",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_roles",
        "is_builtin",
        existing_type=sa.BOOLEAN(),
        comment="是否内置角色",
        existing_comment="是否内置角色（不可删除）",
        existing_nullable=False,
    )
    op.create_table_comment(
        "tenant_permissions", "租户权限表", existing_comment="租户权限表（全局定义，所有租户共享权限点）", schema=None
    )
    op.alter_column(
        "tenant_permissions",
        "menu_icon",
        existing_type=sa.VARCHAR(length=64),
        comment="菜单图标",
        existing_comment="菜单图标，如 lucide:inbox",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_permissions",
        "menu_path",
        existing_type=sa.VARCHAR(length=256),
        comment="关联的菜单路径",
        existing_comment="关联的菜单路径，如 /app/feedback",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_permissions",
        "type",
        existing_type=sa.VARCHAR(length=20),
        comment="类型",
        existing_comment="类型: module, action",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_permissions",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment="权限代码",
        existing_comment="权限代码，如 feedback:view",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
