"""add_details_to_priority_score

Revision ID: eb4f2977a7fb
Revises: 3a4b5c6d7e8f
Create Date: 2026-01-06 23:58:20.953108

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb4f2977a7fb'
down_revision = '3a4b5c6d7e8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority_scores', sa.Column('details', sa.JSON(), nullable=True, comment='详细计算结果'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority_scores', 'details')
    op.add_column(
        'feedbacks',
        sa.Column('title', sa.VARCHAR(length=400), autoincrement=False, nullable=True, comment='反馈标题（可选）'),
    )
    # ### end Alembic commands ###
