"""sync_invitation_system_models

Revision ID: e1a0f801a981
Revises: a5b1d6a5e259
Create Date: 2026-01-19 23:01:04.666642

"""

from alembic import op
import sqlalchemy as sa
import backend.common.model
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1a0f801a981"
down_revision = "a5b1d6a5e259"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_blacklist",
        sa.Column("created_time", backend.common.model.TimeZone(timezone=True), nullable=False, comment="创建时间"),
    )
    op.add_column(
        "email_blacklist",
        sa.Column("updated_time", backend.common.model.TimeZone(timezone=True), nullable=True, comment="更新时间"),
    )
    op.alter_column(
        "email_blacklist",
        "type",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_comment="类型: disposable/spam/banned",
        existing_nullable=False,
    )
    op.alter_column(
        "email_blacklist",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="是否启用",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("email_blacklist_domain_key"), "email_blacklist", type_="unique")
    op.drop_index(
        op.f("idx_email_blacklist_active"), table_name="email_blacklist", postgresql_where="(is_active = true)"
    )
    op.drop_index(op.f("idx_email_blacklist_domain"), table_name="email_blacklist")
    op.create_index(op.f("ix_email_blacklist_domain"), "email_blacklist", ["domain"], unique=True)
    op.create_index(op.f("ix_email_blacklist_is_active"), "email_blacklist", ["is_active"], unique=False)
    op.drop_constraint(op.f("email_blacklist_added_by_fkey"), "email_blacklist", type_="foreignkey")
    op.create_table_comment("email_blacklist", "邮箱黑名单表", existing_comment=None, schema=None)
    op.drop_column("email_blacklist", "created_at")
    op.drop_column("email_blacklist", "updated_at")
    op.add_column(
        "email_verifications",
        sa.Column("created_time", backend.common.model.TimeZone(timezone=True), nullable=False, comment="创建时间"),
    )
    op.add_column(
        "email_verifications",
        sa.Column("updated_time", backend.common.model.TimeZone(timezone=True), nullable=True, comment="更新时间"),
    )
    op.alter_column(
        "email_verifications",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="是否已验证",
        existing_nullable=False,
    )
    op.alter_column(
        "email_verifications",
        "send_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="发送次数",
        existing_nullable=False,
    )
    op.alter_column(
        "email_verifications",
        "last_sent_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="上次发送时间",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("idx_email_verifications_active"),
        table_name="email_verifications",
        postgresql_where="(is_verified = false)",
    )
    op.drop_index(op.f("idx_email_verifications_code"), table_name="email_verifications")
    op.drop_index(op.f("idx_email_verifications_email"), table_name="email_verifications")
    op.drop_index(op.f("idx_email_verifications_user"), table_name="email_verifications")
    op.create_index(op.f("ix_email_verifications_email"), "email_verifications", ["email"], unique=False)
    op.create_index(op.f("ix_email_verifications_user_id"), "email_verifications", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_email_verifications_verification_code"), "email_verifications", ["verification_code"], unique=False
    )
    op.create_table_comment("email_verifications", "邮箱验证记录表", existing_comment=None, schema=None)
    op.drop_column("email_verifications", "created_at")
    op.drop_column("email_verifications", "updated_at")
    op.add_column(
        "invitation_usage",
        sa.Column("created_time", backend.common.model.TimeZone(timezone=True), nullable=False, comment="创建时间"),
    )
    op.add_column(
        "invitation_usage",
        sa.Column("updated_time", backend.common.model.TimeZone(timezone=True), nullable=True, comment="更新时间"),
    )
    op.alter_column(
        "invitation_usage",
        "completed_onboarding",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="是否完成引导",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_invitation_usage_date"), table_name="invitation_usage")
    op.drop_index(op.f("idx_invitation_usage_email"), table_name="invitation_usage")
    op.drop_index(op.f("idx_invitation_usage_invitation"), table_name="invitation_usage")
    op.drop_index(op.f("idx_invitation_usage_ip"), table_name="invitation_usage")
    op.drop_index(op.f("idx_invitation_usage_user"), table_name="invitation_usage")
    op.create_index(op.f("ix_invitation_usage_invitation_id"), "invitation_usage", ["invitation_id"], unique=False)
    op.create_index(op.f("ix_invitation_usage_ip_address"), "invitation_usage", ["ip_address"], unique=False)
    op.create_index(
        op.f("ix_invitation_usage_registered_email"), "invitation_usage", ["registered_email"], unique=False
    )
    op.create_index(op.f("ix_invitation_usage_user_id"), "invitation_usage", ["user_id"], unique=False)
    op.drop_constraint(op.f("invitation_usage_created_tenant_id_fkey"), "invitation_usage", type_="foreignkey")
    op.create_table_comment("invitation_usage", "邀请使用记录表", existing_comment=None, schema=None)
    op.drop_column("invitation_usage", "used_at")
    op.drop_column("invitation_usage", "updated_at")
    op.add_column(
        "invitations",
        sa.Column("created_time", backend.common.model.TimeZone(timezone=True), nullable=False, comment="创建时间"),
    )
    op.add_column(
        "invitations",
        sa.Column("updated_time", backend.common.model.TimeZone(timezone=True), nullable=True, comment="更新时间"),
    )
    op.alter_column(
        "invitations",
        "usage_limit",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="使用次数限制",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "used_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="已使用次数",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "plan_code",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_comment="赋予的套餐代号",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "trial_days",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="试用天数",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_comment="状态: active/expired/disabled",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_invitations_creator"), table_name="invitations")
    op.drop_index(op.f("idx_invitations_expires"), table_name="invitations")
    op.drop_index(op.f("idx_invitations_status"), table_name="invitations")
    op.drop_index(op.f("idx_invitations_token"), table_name="invitations")
    op.drop_constraint(op.f("invitations_token_key"), "invitations", type_="unique")
    op.create_index(op.f("ix_invitations_status"), "invitations", ["status"], unique=False)
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.drop_constraint(op.f("invitations_creator_id_fkey"), "invitations", type_="foreignkey")
    op.create_table_comment("invitations", "邀请表", existing_comment=None, schema=None)
    op.drop_column("invitations", "created_at")
    op.drop_column("invitations", "updated_at")
    op.alter_column(
        "sys_user", "invitation_id", existing_type=sa.VARCHAR(length=36), comment="邀请ID", existing_nullable=True
    )
    op.alter_column(
        "sys_user",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        nullable=False,
        comment="邮箱是否已验证",
    )
    op.drop_index(op.f("idx_sys_user_email_verified"), table_name="sys_user")
    op.drop_index(op.f("idx_sys_user_invitation"), table_name="sys_user")
    op.drop_constraint(op.f("sys_user_invitation_id_fkey"), "sys_user", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("sys_user_invitation_id_fkey"), "sys_user", "invitations", ["invitation_id"], ["id"], ondelete="SET NULL"
    )
    op.create_index(op.f("idx_sys_user_invitation"), "sys_user", ["invitation_id"], unique=False)
    op.create_index(op.f("idx_sys_user_email_verified"), "sys_user", ["email_verified"], unique=False)
    op.alter_column(
        "sys_user",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        nullable=True,
        comment=None,
        existing_comment="邮箱是否已验证",
    )
    op.alter_column(
        "sys_user",
        "invitation_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="邀请ID",
        existing_nullable=True,
    )
    op.add_column(
        "invitations",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="更新时间"
        ),
    )
    op.add_column(
        "invitations",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="创建时间",
        ),
    )
    op.drop_table_comment("invitations", existing_comment="邀请表", schema=None)
    op.create_foreign_key(
        op.f("invitations_creator_id_fkey"), "invitations", "sys_user", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_status"), table_name="invitations")
    op.create_unique_constraint(
        op.f("invitations_token_key"), "invitations", ["token"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_invitations_token"), "invitations", ["token"], unique=False)
    op.create_index(op.f("idx_invitations_status"), "invitations", ["status"], unique=False)
    op.create_index(op.f("idx_invitations_expires"), "invitations", ["expires_at"], unique=False)
    op.create_index(op.f("idx_invitations_creator"), "invitations", ["creator_id"], unique=False)
    op.alter_column(
        "invitations",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'active'::character varying"),
        existing_comment="状态: active/expired/disabled",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "trial_days",
        existing_type=sa.INTEGER(),
        server_default=sa.text("90"),
        existing_comment="试用天数",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "plan_code",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'pro'::character varying"),
        existing_comment="赋予的套餐代号",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "used_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="已使用次数",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "usage_limit",
        existing_type=sa.INTEGER(),
        server_default=sa.text("10"),
        existing_comment="使用次数限制",
        existing_nullable=False,
    )
    op.drop_column("invitations", "updated_time")
    op.drop_column("invitations", "created_time")
    op.add_column(
        "invitation_usage",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="更新时间"
        ),
    )
    op.add_column(
        "invitation_usage",
        sa.Column(
            "used_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="使用时间",
        ),
    )
    op.drop_table_comment("invitation_usage", existing_comment="邀请使用记录表", schema=None)
    op.create_foreign_key(
        op.f("invitation_usage_created_tenant_id_fkey"),
        "invitation_usage",
        "tenants",
        ["created_tenant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_invitation_usage_user_id"), table_name="invitation_usage")
    op.drop_index(op.f("ix_invitation_usage_registered_email"), table_name="invitation_usage")
    op.drop_index(op.f("ix_invitation_usage_ip_address"), table_name="invitation_usage")
    op.drop_index(op.f("ix_invitation_usage_invitation_id"), table_name="invitation_usage")
    op.create_index(op.f("idx_invitation_usage_user"), "invitation_usage", ["user_id"], unique=False)
    op.create_index(op.f("idx_invitation_usage_ip"), "invitation_usage", ["ip_address"], unique=False)
    op.create_index(op.f("idx_invitation_usage_invitation"), "invitation_usage", ["invitation_id"], unique=False)
    op.create_index(op.f("idx_invitation_usage_email"), "invitation_usage", ["registered_email"], unique=False)
    op.create_index(op.f("idx_invitation_usage_date"), "invitation_usage", ["used_at"], unique=False)
    op.alter_column(
        "invitation_usage",
        "completed_onboarding",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="是否完成引导",
        existing_nullable=False,
    )
    op.drop_column("invitation_usage", "updated_time")
    op.drop_column("invitation_usage", "created_time")
    op.add_column(
        "email_verifications",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="更新时间"
        ),
    )
    op.add_column(
        "email_verifications",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="创建时间",
        ),
    )
    op.drop_table_comment("email_verifications", existing_comment="邮箱验证记录表", schema=None)
    op.drop_index(op.f("ix_email_verifications_verification_code"), table_name="email_verifications")
    op.drop_index(op.f("ix_email_verifications_user_id"), table_name="email_verifications")
    op.drop_index(op.f("ix_email_verifications_email"), table_name="email_verifications")
    op.create_index(op.f("idx_email_verifications_user"), "email_verifications", ["user_id"], unique=False)
    op.create_index(op.f("idx_email_verifications_email"), "email_verifications", ["email"], unique=False)
    op.create_index(op.f("idx_email_verifications_code"), "email_verifications", ["verification_code"], unique=False)
    op.create_index(
        op.f("idx_email_verifications_active"),
        "email_verifications",
        ["user_id"],
        unique=True,
        postgresql_where="(is_verified = false)",
    )
    op.alter_column(
        "email_verifications",
        "last_sent_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_comment="上次发送时间",
        existing_nullable=False,
    )
    op.alter_column(
        "email_verifications",
        "send_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_comment="发送次数",
        existing_nullable=False,
    )
    op.alter_column(
        "email_verifications",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="是否已验证",
        existing_nullable=False,
    )
    op.drop_column("email_verifications", "updated_time")
    op.drop_column("email_verifications", "created_time")
    op.add_column(
        "email_blacklist",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="更新时间"
        ),
    )
    op.add_column(
        "email_blacklist",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="创建时间",
        ),
    )
    op.drop_table_comment("email_blacklist", existing_comment="邮箱黑名单表", schema=None)
    op.create_foreign_key(
        op.f("email_blacklist_added_by_fkey"), "email_blacklist", "sys_user", ["added_by"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_email_blacklist_is_active"), table_name="email_blacklist")
    op.drop_index(op.f("ix_email_blacklist_domain"), table_name="email_blacklist")
    op.create_index(op.f("idx_email_blacklist_domain"), "email_blacklist", ["domain"], unique=False)
    op.create_index(
        op.f("idx_email_blacklist_active"),
        "email_blacklist",
        ["is_active"],
        unique=False,
        postgresql_where="(is_active = true)",
    )
    op.create_unique_constraint(
        op.f("email_blacklist_domain_key"), "email_blacklist", ["domain"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "email_blacklist",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="是否启用",
        existing_nullable=False,
    )
    op.alter_column(
        "email_blacklist",
        "type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'disposable'::character varying"),
        existing_comment="类型: disposable/spam/banned",
        existing_nullable=False,
    )
    op.drop_column("email_blacklist", "updated_time")
    op.drop_column("email_blacklist", "created_time")
    # ### end Alembic commands ###
