"""add_subscription_tables

Revision ID: 2d6098f3eae5
Revises: 07e015954d69
Create Date: 2026-01-17 23:04:14.267874

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d6098f3eae5'
down_revision = '07e015954d69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscription_plans',
        sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
        sa.Column('code', sa.String(length=20), nullable=False, comment='套餐代号: starter/pro/flagship/enterprise'),
        sa.Column('name', sa.String(length=50), nullable=False, comment='套餐名称（启航版、专业版...）'),
        sa.Column('description', sa.Text(), nullable=True, comment='套餐描述'),
        sa.Column('price_monthly', sa.Integer(), nullable=False, comment='月付价格（分）'),
        sa.Column('price_yearly', sa.Integer(), nullable=False, comment='年付价格（分）'),
        sa.Column('seat_limit', sa.Integer(), nullable=False, comment='席位上限（-1 表示不限）'),
        sa.Column('feedback_limit', sa.Integer(), nullable=False, comment='反馈存储上限（-1 表示不限）'),
        sa.Column('ai_credits_monthly', sa.Integer(), nullable=False, comment='月度 AI 积分'),
        sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='功能开关和配置'),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
        sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    op.create_index('idx_subscription_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('idx_subscription_plan_code', 'subscription_plans', ['code'], unique=False)
    op.create_table(
        'tenant_subscriptions',
        sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
        sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='租户ID'),
        sa.Column('plan_id', sa.String(length=36), nullable=False, comment='套餐ID'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='订阅状态'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='订阅开始时间'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='订阅到期时间'),
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='试用期结束时间'),
        sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True, comment='取消时间'),
        sa.Column('source', sa.String(length=20), nullable=False, comment='订阅来源'),
        sa.Column('payment_id', sa.String(length=100), nullable=True, comment='支付订单ID（预留）'),
        sa.Column('created_by', sa.String(length=36), nullable=True, comment='创建人（手动添加时为管理员ID）'),
        sa.Column('notes', sa.Text(), nullable=True, comment='管理备注'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_tenant_subscription_expires', 'tenant_subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_tenant_subscription_status', 'tenant_subscriptions', ['status'], unique=False)
    op.create_index('idx_tenant_subscription_tenant', 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table(
        'subscription_history',
        sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
        sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='租户ID'),
        sa.Column('subscription_id', sa.String(length=36), nullable=False, comment='订阅ID'),
        sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型'),
        sa.Column('old_plan_code', sa.String(length=20), nullable=True, comment='变更前套餐代号'),
        sa.Column('new_plan_code', sa.String(length=20), nullable=False, comment='变更后套餐代号'),
        sa.Column('changed_by', sa.String(length=36), nullable=True, comment='操作人ID'),
        sa.Column('reason', sa.Text(), nullable=True, comment='变更原因/备注'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_subscription_history_created', 'subscription_history', ['created_at'], unique=False)
    op.create_index('idx_subscription_history_subscription', 'subscription_history', ['subscription_id'], unique=False)
    op.create_index('idx_subscription_history_tenant', 'subscription_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscription_history_tenant_id'), 'subscription_history', ['tenant_id'], unique=False)
    op.alter_column('credits_config', 'id', existing_type=sa.VARCHAR(length=36), comment='ID', existing_nullable=False)
    op.alter_column(
        'credits_config', 'config_key', existing_type=sa.VARCHAR(length=50), comment='配置键', existing_nullable=False
    )
    op.alter_column(
        'credits_config', 'config_value', existing_type=sa.INTEGER(), comment='配置值（整数）', existing_nullable=False
    )
    op.alter_column(
        'credits_config',
        'config_type',
        existing_type=sa.VARCHAR(length=20),
        comment='配置类型: operation_cost / plan_quota',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_config', 'description', existing_type=sa.TEXT(), comment='配置说明', existing_nullable=True
    )
    op.drop_column('credits_config', 'updated_at')
    op.drop_column('credits_config', 'created_at')
    op.alter_column(
        'credits_usage_log', 'id', existing_type=sa.VARCHAR(length=36), comment='ID', existing_nullable=False
    )
    op.alter_column(
        'credits_usage_log', 'tenant_id', existing_type=sa.VARCHAR(length=36), comment='租户ID', existing_nullable=False
    )
    op.alter_column(
        'credits_usage_log',
        'user_id',
        existing_type=sa.VARCHAR(length=36),
        comment='操作用户ID',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'operation_type',
        existing_type=sa.VARCHAR(length=50),
        comment='操作类型',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_usage_log', 'credits_cost', existing_type=sa.INTEGER(), comment='消耗积分', existing_nullable=False
    )
    op.alter_column(
        'credits_usage_log',
        'description',
        existing_type=sa.VARCHAR(length=255),
        comment='操作描述',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'extra_data',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='扩展信息',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=False,
        comment='创建时间',
    )
    op.alter_column(
        'feedbacks',
        'author_type',
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_comment='来源类型: customer=内部客户, external=外部用户',
        existing_nullable=False,
    )
    op.alter_column(
        'sys_user',
        'username',
        existing_type=sa.VARCHAR(length=64),
        comment='用户名(显示用)',
        existing_comment='用户名',
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=False)
    op.alter_column('tenant_credits', 'id', existing_type=sa.VARCHAR(length=36), comment='ID', existing_nullable=False)
    op.alter_column(
        'tenant_credits', 'tenant_id', existing_type=sa.VARCHAR(length=36), comment='租户ID', existing_nullable=False
    )
    op.alter_column(
        'tenant_credits',
        'plan_type',
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        comment='订阅类型: starter/pro/team/enterprise',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'monthly_quota',
        existing_type=sa.INTEGER(),
        server_default=None,
        comment='月度积分额度',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'current_balance',
        existing_type=sa.INTEGER(),
        server_default=None,
        comment='当前剩余积分',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'total_used',
        existing_type=sa.INTEGER(),
        server_default=None,
        comment='累计使用积分',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'last_refresh_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='上次刷新时间',
        existing_nullable=True,
    )
    op.alter_column(
        'tenant_credits',
        'next_refresh_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='下次刷新时间',
        existing_nullable=True,
    )
    op.drop_column('tenant_credits', 'updated_at')
    op.drop_column('tenant_credits', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenant_credits',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'tenant_credits',
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        'tenant_credits',
        'next_refresh_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='下次刷新时间',
        existing_nullable=True,
    )
    op.alter_column(
        'tenant_credits',
        'last_refresh_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='上次刷新时间',
        existing_nullable=True,
    )
    op.alter_column(
        'tenant_credits',
        'total_used',
        existing_type=sa.INTEGER(),
        server_default=sa.text('0'),
        comment=None,
        existing_comment='累计使用积分',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'current_balance',
        existing_type=sa.INTEGER(),
        server_default=sa.text('500'),
        comment=None,
        existing_comment='当前剩余积分',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'monthly_quota',
        existing_type=sa.INTEGER(),
        server_default=sa.text('500'),
        comment=None,
        existing_comment='月度积分额度',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'plan_type',
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'starter'::character varying"),
        comment=None,
        existing_comment='订阅类型: starter/pro/team/enterprise',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'tenant_id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='租户ID',
        existing_nullable=False,
    )
    op.alter_column(
        'tenant_credits',
        'id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='ID',
        existing_nullable=False,
    )
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.alter_column(
        'sys_user',
        'username',
        existing_type=sa.VARCHAR(length=64),
        comment='用户名',
        existing_comment='用户名(显示用)',
        existing_nullable=True,
    )
    op.alter_column(
        'feedbacks',
        'author_type',
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'customer'::character varying"),
        existing_comment='来源类型: customer=内部客户, external=外部用户',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_usage_log',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        nullable=True,
        comment=None,
        existing_comment='创建时间',
    )
    op.alter_column(
        'credits_usage_log',
        'extra_data',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment='扩展信息',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'description',
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment='操作描述',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'credits_cost',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='消耗积分',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_usage_log',
        'operation_type',
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment='操作类型',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_usage_log',
        'user_id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='操作用户ID',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_usage_log',
        'tenant_id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='租户ID',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_usage_log',
        'id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='ID',
        existing_nullable=False,
    )
    op.add_column(
        'credits_config',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'credits_config',
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        'credits_config',
        'description',
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment='配置说明',
        existing_nullable=True,
    )
    op.alter_column(
        'credits_config',
        'config_type',
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment='配置类型: operation_cost / plan_quota',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_config',
        'config_value',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='配置值（整数）',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_config',
        'config_key',
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment='配置键',
        existing_nullable=False,
    )
    op.alter_column(
        'credits_config',
        'id',
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment='ID',
        existing_nullable=False,
    )
    op.drop_index(op.f('ix_subscription_history_tenant_id'), table_name='subscription_history')
    op.drop_index('idx_subscription_history_tenant', table_name='subscription_history')
    op.drop_index('idx_subscription_history_subscription', table_name='subscription_history')
    op.drop_index('idx_subscription_history_created', table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.drop_index('idx_tenant_subscription_tenant', table_name='tenant_subscriptions')
    op.drop_index('idx_tenant_subscription_status', table_name='tenant_subscriptions')
    op.drop_index('idx_tenant_subscription_expires', table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index('idx_subscription_plan_code', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
