"""fix_batch_job_timezone_fields

Revision ID: 1088af5f70cf
Revises: 0eb2e0b8cbe5
Create Date: 2026-02-05 21:07:40.290899

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1088af5f70cf'
down_revision = '0eb2e0b8cbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_job', 'started_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=backend.common.model.TimeZone(timezone=True),
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('batch_job', 'completed_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=backend.common.model.TimeZone(timezone=True),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('batch_task_item', 'started_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=backend.common.model.TimeZone(timezone=True),
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('batch_task_item', 'completed_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=backend.common.model.TimeZone(timezone=True),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='建议ID',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'cluster_label',
               existing_type=sa.INTEGER(),
               comment='聚类标签',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_id',
               existing_type=sa.VARCHAR(length=50),
               comment='建议关联的需求ID',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_title',
               existing_type=sa.VARCHAR(length=500),
               comment='建议关联的需求标题',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_status',
               existing_type=sa.VARCHAR(length=50),
               comment='建议关联的需求状态',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_category',
               existing_type=sa.VARCHAR(length=100),
               comment='建议关联的需求分类',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'feedback_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='反馈数量',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_comment='建议状态: pending(待处理), accepted(已接受-关联), rejected(已拒绝), create_new(创建新需求)',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'processed_by',
               existing_type=sa.VARCHAR(length=50),
               comment='处理人ID',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='处理时间',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删除）',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merge_suggestion', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_merge_suggestion_status'), table_name='merge_suggestion', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_merge_suggestion_tenant'), table_name='merge_suggestion', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_merge_suggestion_topic'), table_name='merge_suggestion', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_merge_suggestion_status'), 'merge_suggestion', ['status'], unique=False)
    op.create_index(op.f('ix_merge_suggestion_suggested_topic_id'), 'merge_suggestion', ['suggested_topic_id'], unique=False)
    op.create_index(op.f('ix_merge_suggestion_tenant_id'), 'merge_suggestion', ['tenant_id'], unique=False)
    op.create_table_comment(
        'merge_suggestion',
        '\n    合并建议表 - 聚类后发现的重复需求建议\n\n    当聚类发现某些反馈与已有需求高度相似时（similarity >= 0.80），\n    生成合并建议，由用户决策是否关联到已有需求或创建新需求。\n    ',
        existing_comment='合并建议表 - 聚类后发现的重复需求建议',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'merge_suggestion',
        '合并建议表 - 聚类后发现的重复需求建议',
        existing_comment='\n    合并建议表 - 聚类后发现的重复需求建议\n\n    当聚类发现某些反馈与已有需求高度相似时（similarity >= 0.80），\n    生成合并建议，由用户决策是否关联到已有需求或创建新需求。\n    ',
        schema=None
    )
    op.drop_index(op.f('ix_merge_suggestion_tenant_id'), table_name='merge_suggestion')
    op.drop_index(op.f('ix_merge_suggestion_suggested_topic_id'), table_name='merge_suggestion')
    op.drop_index(op.f('ix_merge_suggestion_status'), table_name='merge_suggestion')
    op.create_index(op.f('idx_merge_suggestion_topic'), 'merge_suggestion', ['suggested_topic_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_merge_suggestion_tenant'), 'merge_suggestion', ['tenant_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_merge_suggestion_status'), 'merge_suggestion', ['tenant_id', 'status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('merge_suggestion', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merge_suggestion', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merge_suggestion', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删除）',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='处理时间',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'processed_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='处理人ID',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_comment='建议状态: pending(待处理), accepted(已接受-关联), rejected(已拒绝), create_new(创建新需求)',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'feedback_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='反馈数量',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='建议关联的需求分类',
               existing_nullable=True)
    op.alter_column('merge_suggestion', 'suggested_topic_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='建议关联的需求状态',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='建议关联的需求标题',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'suggested_topic_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='建议关联的需求ID',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'cluster_label',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='聚类标签',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('merge_suggestion', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='建议ID',
               existing_nullable=False)
    op.alter_column('batch_task_item', 'completed_time',
               existing_type=backend.common.model.TimeZone(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('batch_task_item', 'started_time',
               existing_type=backend.common.model.TimeZone(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('batch_job', 'completed_time',
               existing_type=backend.common.model.TimeZone(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('batch_job', 'started_time',
               existing_type=backend.common.model.TimeZone(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='开始时间',
               existing_nullable=True)
    # ### end Alembic commands ###
